name: Build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    container:
      image: fedora:latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo dnf --assumeyes install @c-development dnf-plugins-core
          sudo dnf builddep --assumeyes --spec package/abrt-java-connector.spec

      - name: Build
        run: |
          cmake -S . -B build
          make -C build

      - name: Run tests
        run: make -C build test
